# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTRUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=32)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('lastLoginDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
