# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d19app', '0002_ctrecordmodel_ctrecordpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctrecordpoint',
            name='recordDate',
        ),
        migrations.AddField(
            model_name='ctrecordpoint',
            name='timestamp',
            field=models.CharField(default=b'0.0', max_length=128),
        ),
    ]
