# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('d19app', '0003_auto_20151230_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrecordmodel',
            name='recordDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
