# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d19app', '0004_ctrecordmodel_recorddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctrecordmodel',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ctrecordpoint',
            old_name='recordId',
            new_name='fatherRecord',
        ),
    ]
